/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;
import clientAdm.Cliente;
import controller.*;
import java.awt.CardLayout;
import java.io.IOException;
import java.util.Collections;
import java.util.Iterator;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import model.*;

/**
 *
 * @author lablenda3
 */
public class TelaPrincipal extends javax.swing.JFrame {
    
    /**
     * Atributo controller que gerencia algumas ações a serem realizadas no sistema.
     */
    private static ControllerGerenciador gerenciador = new ControllerGerenciador();
    
    /**
     * Atributo controller que gerencia o envio dos dados desejados.
     */
    private static ControllerRede rede = new ControllerRede();
    
    /**
     * Atributo controller que gerencia ações da corrida.
     */
    private static ControllerCorrida corrida = new ControllerCorrida();
    
    /**
     * Atributo cliente responsável por fazer conexão com o servidor.
     */
    private static Cliente adm;
    
    /**
     * Creates new form TelaPrincipal
     * @throws java.io.IOException
     */
    public TelaPrincipal() throws IOException {
        initComponents();
        mostrarMenuPrincipal(false);
        conectarCliente();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        JpPrincipal = new javax.swing.JPanel();
        telaLogin = new javax.swing.JPanel();
        jLabel23 = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        jLabel25 = new javax.swing.JLabel();
        userAdmLogin = new javax.swing.JTextField();
        jLabel26 = new javax.swing.JLabel();
        jLabel27 = new javax.swing.JLabel();
        senhaAdmLogin = new javax.swing.JPasswordField();
        loginAdm = new javax.swing.JButton();
        JpHome = new javax.swing.JPanel();
        jLabel30 = new javax.swing.JLabel();
        jLabel31 = new javax.swing.JLabel();
        jLabel32 = new javax.swing.JLabel();
        jLabel33 = new javax.swing.JLabel();
        jpCardCarro = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        idCarro = new javax.swing.JTextField();
        equipeCarro = new javax.swing.JTextField();
        numeroCarro = new javax.swing.JTextField();
        salvarCarro = new javax.swing.JButton();
        pegarIDCarro = new javax.swing.JButton();
        jpCadAdm = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        nomeAdm = new javax.swing.JTextField();
        salvarAdm = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        senhaAdm = new javax.swing.JPasswordField();
        JpPiloto = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        nomePiloto = new javax.swing.JTextField();
        salvarPiloto = new javax.swing.JButton();
        JpRemoveCar = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        removeCar = new javax.swing.JTable();
        jLabel10 = new javax.swing.JLabel();
        removerCarro = new javax.swing.JButton();
        jpRemoverPiloto = new javax.swing.JPanel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        pilotoRemover = new javax.swing.JTextField();
        removerPiloto = new javax.swing.JButton();
        jpCriarCorrida = new javax.swing.JPanel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        voltasQualificacao = new javax.swing.JTextField();
        voltasCorrida = new javax.swing.JTextField();
        criarCorrida = new javax.swing.JButton();
        jLabel22 = new javax.swing.JLabel();
        confirmarPiloto = new javax.swing.JButton();
        jScrollPane5 = new javax.swing.JScrollPane();
        escolherPiloto = new javax.swing.JTable();
        jScrollPane3 = new javax.swing.JScrollPane();
        escolherCarro = new javax.swing.JTable();
        jLabel28 = new javax.swing.JLabel();
        JpRank = new javax.swing.JPanel();
        jLabel16 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jRank = new javax.swing.JTable();
        JpgerenciarCorrida = new javax.swing.JPanel();
        jLabel18 = new javax.swing.JLabel();
        comecarCorrida = new javax.swing.JButton();
        pausarCorrida = new javax.swing.JButton();
        reiniciarCorrida = new javax.swing.JButton();
        pilotosCad = new javax.swing.JPanel();
        jScrollPane4 = new javax.swing.JScrollPane();
        verPilotosCadastrados = new javax.swing.JTable();
        jLabel19 = new javax.swing.JLabel();
        menuPrincipal = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        cadAdm = new javax.swing.JMenuItem();
        CadCarro = new javax.swing.JMenuItem();
        cadPiloto = new javax.swing.JMenuItem();
        pilotosCadastrados = new javax.swing.JMenu();
        cadCorrida = new javax.swing.JMenuItem();
        gerenciarRace = new javax.swing.JMenuItem();
        pilotosRegisters = new javax.swing.JMenuItem();
        jMenu4 = new javax.swing.JMenu();
        removePiloto = new javax.swing.JMenuItem();
        removeCarro = new javax.swing.JMenuItem();
        rank = new javax.swing.JMenu();
        visualizarRank = new javax.swing.JMenuItem();
        outrasOpcoes = new javax.swing.JMenu();
        home_page = new javax.swing.JMenuItem();
        logout = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Cliente Administrador");
        setResizable(false);

        JpPrincipal.setPreferredSize(new java.awt.Dimension(821, 710));
        JpPrincipal.setLayout(new java.awt.CardLayout());

        telaLogin.setBackground(new java.awt.Color(255, 255, 255));

        jLabel23.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/cadAdm.png"))); // NOI18N

        jLabel24.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        jLabel24.setText("Login");

        jLabel26.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        jLabel26.setText("Usuário:");

        jLabel27.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        jLabel27.setText("Senha:");

        loginAdm.setText("Login");
        loginAdm.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                loginAdmActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout telaLoginLayout = new javax.swing.GroupLayout(telaLogin);
        telaLogin.setLayout(telaLoginLayout);
        telaLoginLayout.setHorizontalGroup(
            telaLoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(telaLoginLayout.createSequentialGroup()
                .addGroup(telaLoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(telaLoginLayout.createSequentialGroup()
                        .addGap(360, 360, 360)
                        .addComponent(jLabel23))
                    .addGroup(telaLoginLayout.createSequentialGroup()
                        .addGap(370, 370, 370)
                        .addComponent(jLabel24))
                    .addGroup(telaLoginLayout.createSequentialGroup()
                        .addGroup(telaLoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(telaLoginLayout.createSequentialGroup()
                                .addGap(306, 306, 306)
                                .addComponent(jLabel25))
                            .addComponent(jLabel26, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel27, javax.swing.GroupLayout.Alignment.TRAILING))
                        .addGap(18, 18, 18)
                        .addGroup(telaLoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(userAdmLogin)
                            .addComponent(senhaAdmLogin, javax.swing.GroupLayout.DEFAULT_SIZE, 225, Short.MAX_VALUE)))
                    .addGroup(telaLoginLayout.createSequentialGroup()
                        .addGap(372, 372, 372)
                        .addComponent(loginAdm, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(272, Short.MAX_VALUE))
        );
        telaLoginLayout.setVerticalGroup(
            telaLoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(telaLoginLayout.createSequentialGroup()
                .addGap(56, 56, 56)
                .addComponent(jLabel23)
                .addGap(18, 18, 18)
                .addComponent(jLabel24)
                .addGap(38, 38, 38)
                .addGroup(telaLoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel26, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(userAdmLogin))
                .addGap(25, 25, 25)
                .addGroup(telaLoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel27)
                    .addComponent(senhaAdmLogin, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(loginAdm, javax.swing.GroupLayout.DEFAULT_SIZE, 36, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel25)
                .addGap(322, 322, 322))
        );

        JpPrincipal.add(telaLogin, "tela de login");

        jLabel30.setFont(new java.awt.Font("Ubuntu Condensed", 1, 48)); // NOI18N
        jLabel30.setText("Autorama Inteligente ");

        jLabel31.setFont(new java.awt.Font("Ubuntu Condensed", 1, 48)); // NOI18N
        jLabel31.setText("M.I Concorrência e Conectividade");

        jLabel32.setFont(new java.awt.Font("Ubuntu Condensed", 1, 48)); // NOI18N
        jLabel32.setText("do");

        jLabel33.setFont(new java.awt.Font("Ubuntu", 2, 24)); // NOI18N
        jLabel33.setText("Copyright: Gabriel Sá e Samuel");

        javax.swing.GroupLayout JpHomeLayout = new javax.swing.GroupLayout(JpHome);
        JpHome.setLayout(JpHomeLayout);
        JpHomeLayout.setHorizontalGroup(
            JpHomeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(JpHomeLayout.createSequentialGroup()
                .addGroup(JpHomeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(JpHomeLayout.createSequentialGroup()
                        .addGap(348, 348, 348)
                        .addComponent(jLabel32))
                    .addGroup(JpHomeLayout.createSequentialGroup()
                        .addGap(155, 155, 155)
                        .addComponent(jLabel30))
                    .addGroup(JpHomeLayout.createSequentialGroup()
                        .addGap(214, 214, 214)
                        .addComponent(jLabel33))
                    .addGroup(JpHomeLayout.createSequentialGroup()
                        .addGap(45, 45, 45)
                        .addComponent(jLabel31)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        JpHomeLayout.setVerticalGroup(
            JpHomeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(JpHomeLayout.createSequentialGroup()
                .addGap(65, 65, 65)
                .addComponent(jLabel30)
                .addGap(39, 39, 39)
                .addComponent(jLabel32, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(31, 31, 31)
                .addComponent(jLabel31)
                .addGap(151, 151, 151)
                .addComponent(jLabel33)
                .addContainerGap(241, Short.MAX_VALUE))
        );

        JpPrincipal.add(JpHome, "home");

        jLabel4.setFont(new java.awt.Font("Ubuntu", 1, 36)); // NOI18N
        jLabel4.setText("Cadastro de Carro");

        jLabel5.setFont(new java.awt.Font("Ubuntu", 1, 36)); // NOI18N
        jLabel5.setText("ID:");

        jLabel6.setFont(new java.awt.Font("Ubuntu", 1, 36)); // NOI18N
        jLabel6.setText("Equipe:");

        jLabel7.setFont(new java.awt.Font("Ubuntu", 1, 36)); // NOI18N
        jLabel7.setText("Número:");

        salvarCarro.setText("Cadastrar");
        salvarCarro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                salvarCarroActionPerformed(evt);
            }
        });

        pegarIDCarro.setText("Pegar ID");
        pegarIDCarro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pegarIDCarroActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jpCardCarroLayout = new javax.swing.GroupLayout(jpCardCarro);
        jpCardCarro.setLayout(jpCardCarroLayout);
        jpCardCarroLayout.setHorizontalGroup(
            jpCardCarroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpCardCarroLayout.createSequentialGroup()
                .addContainerGap(246, Short.MAX_VALUE)
                .addComponent(jLabel4)
                .addGap(264, 264, 264))
            .addGroup(jpCardCarroLayout.createSequentialGroup()
                .addGroup(jpCardCarroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jpCardCarroLayout.createSequentialGroup()
                        .addGap(45, 45, 45)
                        .addComponent(jLabel7))
                    .addGroup(jpCardCarroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jpCardCarroLayout.createSequentialGroup()
                            .addGap(59, 59, 59)
                            .addGroup(jpCardCarroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(jLabel5)
                                .addComponent(jLabel6))
                            .addGap(7, 7, 7)
                            .addGroup(jpCardCarroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(idCarro, javax.swing.GroupLayout.DEFAULT_SIZE, 532, Short.MAX_VALUE)
                                .addComponent(equipeCarro)))
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jpCardCarroLayout.createSequentialGroup()
                            .addContainerGap()
                            .addGroup(jpCardCarroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(jpCardCarroLayout.createSequentialGroup()
                                    .addComponent(salvarCarro, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(158, 158, 158)
                                    .addComponent(pegarIDCarro, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addComponent(numeroCarro, javax.swing.GroupLayout.PREFERRED_SIZE, 529, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jpCardCarroLayout.setVerticalGroup(
            jpCardCarroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpCardCarroLayout.createSequentialGroup()
                .addGap(78, 78, 78)
                .addComponent(jLabel4)
                .addGap(75, 75, 75)
                .addGroup(jpCardCarroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(idCarro, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5))
                .addGap(47, 47, 47)
                .addGroup(jpCardCarroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(equipeCarro, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(67, 67, 67)
                .addGroup(jpCardCarroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(numeroCarro, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(38, 38, 38)
                .addGroup(jpCardCarroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(pegarIDCarro, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(salvarCarro, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(170, Short.MAX_VALUE))
        );

        JpPrincipal.add(jpCardCarro, "Cadastro de novo Carro");

        jpCadAdm.setBackground(new java.awt.Color(250, 255, 255));

        jLabel1.setFont(new java.awt.Font("Ubuntu", 1, 36)); // NOI18N
        jLabel1.setText("Nome:");

        jLabel2.setFont(new java.awt.Font("Ubuntu", 1, 36)); // NOI18N
        jLabel2.setText("Senha:");

        salvarAdm.setText("Salvar");
        salvarAdm.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                salvarAdmActionPerformed(evt);
            }
        });

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/cadAdm.png"))); // NOI18N

        javax.swing.GroupLayout jpCadAdmLayout = new javax.swing.GroupLayout(jpCadAdm);
        jpCadAdm.setLayout(jpCadAdmLayout);
        jpCadAdmLayout.setHorizontalGroup(
            jpCadAdmLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpCadAdmLayout.createSequentialGroup()
                .addGroup(jpCadAdmLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(senhaAdm, javax.swing.GroupLayout.PREFERRED_SIZE, 592, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jpCadAdmLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jpCadAdmLayout.createSequentialGroup()
                            .addGap(65, 65, 65)
                            .addGroup(jpCadAdmLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(jpCadAdmLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel2)
                                    .addComponent(jLabel1))
                                .addGroup(jpCadAdmLayout.createSequentialGroup()
                                    .addGap(3, 3, 3)
                                    .addComponent(nomeAdm, javax.swing.GroupLayout.PREFERRED_SIZE, 589, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGroup(jpCadAdmLayout.createSequentialGroup()
                            .addGap(353, 353, 353)
                            .addComponent(jLabel3))
                        .addGroup(jpCadAdmLayout.createSequentialGroup()
                            .addGap(65, 65, 65)
                            .addComponent(salvarAdm, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(164, Short.MAX_VALUE))
        );
        jpCadAdmLayout.setVerticalGroup(
            jpCadAdmLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpCadAdmLayout.createSequentialGroup()
                .addGap(64, 64, 64)
                .addComponent(jLabel3)
                .addGap(56, 56, 56)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(nomeAdm, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(35, 35, 35)
                .addComponent(jLabel2)
                .addGap(18, 18, 18)
                .addComponent(senhaAdm, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(38, 38, 38)
                .addComponent(salvarAdm, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(173, Short.MAX_VALUE))
        );

        JpPrincipal.add(jpCadAdm, "Cadastro de novo Administrador");

        jLabel8.setFont(new java.awt.Font("Ubuntu", 1, 36)); // NOI18N
        jLabel8.setText("Cadastro de Piloto");

        jLabel9.setFont(new java.awt.Font("Ubuntu", 1, 36)); // NOI18N
        jLabel9.setText("Nome:");

        salvarPiloto.setText("Cadastrar");
        salvarPiloto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                salvarPilotoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout JpPilotoLayout = new javax.swing.GroupLayout(JpPiloto);
        JpPiloto.setLayout(JpPilotoLayout);
        JpPilotoLayout.setHorizontalGroup(
            JpPilotoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(JpPilotoLayout.createSequentialGroup()
                .addGroup(JpPilotoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(JpPilotoLayout.createSequentialGroup()
                        .addGap(56, 56, 56)
                        .addComponent(jLabel9)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(nomePiloto, javax.swing.GroupLayout.PREFERRED_SIZE, 507, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(JpPilotoLayout.createSequentialGroup()
                        .addGap(318, 318, 318)
                        .addComponent(salvarPiloto, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(JpPilotoLayout.createSequentialGroup()
                        .addGap(232, 232, 232)
                        .addComponent(jLabel8)))
                .addContainerGap(142, Short.MAX_VALUE))
        );
        JpPilotoLayout.setVerticalGroup(
            JpPilotoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(JpPilotoLayout.createSequentialGroup()
                .addGap(66, 66, 66)
                .addComponent(jLabel8)
                .addGap(77, 77, 77)
                .addGroup(JpPilotoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel9)
                    .addComponent(nomePiloto, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(44, 44, 44)
                .addComponent(salvarPiloto, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(391, Short.MAX_VALUE))
        );

        JpPrincipal.add(JpPiloto, "Cadastro de Piloto");

        removeCar.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "Equipe", "Número"
            }
        ));
        jScrollPane1.setViewportView(removeCar);

        jLabel10.setFont(new java.awt.Font("Ubuntu", 1, 36)); // NOI18N
        jLabel10.setText("Remover Carro");

        removerCarro.setText("Remover");
        removerCarro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                removerCarroActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout JpRemoveCarLayout = new javax.swing.GroupLayout(JpRemoveCar);
        JpRemoveCar.setLayout(JpRemoveCarLayout);
        JpRemoveCarLayout.setHorizontalGroup(
            JpRemoveCarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, JpRemoveCarLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jLabel10)
                .addGap(328, 328, 328))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, JpRemoveCarLayout.createSequentialGroup()
                .addContainerGap(37, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 678, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(106, 106, 106))
            .addGroup(JpRemoveCarLayout.createSequentialGroup()
                .addGap(306, 306, 306)
                .addComponent(removerCarro, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        JpRemoveCarLayout.setVerticalGroup(
            JpRemoveCarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(JpRemoveCarLayout.createSequentialGroup()
                .addGap(60, 60, 60)
                .addComponent(jLabel10)
                .addGap(32, 32, 32)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(removerCarro, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(87, Short.MAX_VALUE))
        );

        JpPrincipal.add(JpRemoveCar, "Remover carro");

        jLabel11.setFont(new java.awt.Font("Ubuntu", 1, 36)); // NOI18N
        jLabel11.setText("Remover Piloto");

        jLabel12.setFont(new java.awt.Font("Ubuntu", 1, 36)); // NOI18N
        jLabel12.setText("Nome:");

        removerPiloto.setText("Remover");
        removerPiloto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                removerPilotoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jpRemoverPilotoLayout = new javax.swing.GroupLayout(jpRemoverPiloto);
        jpRemoverPiloto.setLayout(jpRemoverPilotoLayout);
        jpRemoverPilotoLayout.setHorizontalGroup(
            jpRemoverPilotoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jpRemoverPilotoLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel11)
                .addGap(325, 325, 325))
            .addGroup(jpRemoverPilotoLayout.createSequentialGroup()
                .addGap(65, 65, 65)
                .addGroup(jpRemoverPilotoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(removerPiloto, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jpRemoverPilotoLayout.createSequentialGroup()
                        .addComponent(jLabel12)
                        .addGap(3, 3, 3)
                        .addComponent(pilotoRemover, javax.swing.GroupLayout.PREFERRED_SIZE, 522, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(121, Short.MAX_VALUE))
        );
        jpRemoverPilotoLayout.setVerticalGroup(
            jpRemoverPilotoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpRemoverPilotoLayout.createSequentialGroup()
                .addGap(69, 69, 69)
                .addComponent(jLabel11)
                .addGap(78, 78, 78)
                .addGroup(jpRemoverPilotoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel12)
                    .addComponent(pilotoRemover, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(30, 30, 30)
                .addComponent(removerPiloto, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(401, Short.MAX_VALUE))
        );

        JpPrincipal.add(jpRemoverPiloto, "Remover piloto");

        jpCriarCorrida.setPreferredSize(new java.awt.Dimension(949, 800));

        jLabel13.setFont(new java.awt.Font("Ubuntu", 1, 18)); // NOI18N
        jLabel13.setText("Corrida:");

        jLabel14.setFont(new java.awt.Font("Ubuntu", 1, 36)); // NOI18N
        jLabel14.setText("Criar nova corrida");

        jLabel17.setFont(new java.awt.Font("Ubuntu", 1, 24)); // NOI18N
        jLabel17.setText("Selecione os pilotos:");

        jLabel20.setFont(new java.awt.Font("Ubuntu", 1, 24)); // NOI18N
        jLabel20.setText("Quantidade de Voltas:");

        jLabel21.setFont(new java.awt.Font("Ubuntu", 1, 18)); // NOI18N
        jLabel21.setText("Sessão de Qualificação");

        criarCorrida.setText("Criar");
        criarCorrida.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                criarCorridaActionPerformed(evt);
            }
        });

        jLabel22.setText("Associe um piloto a um carro e clique em confirmar, faça isso para todos os selecionados");

        confirmarPiloto.setText("Confirmar");
        confirmarPiloto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                confirmarPilotoActionPerformed(evt);
            }
        });

        escolherPiloto.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Nome"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        escolherPiloto.setColumnSelectionAllowed(true);
        escolherPiloto.getTableHeader().setReorderingAllowed(false);
        jScrollPane5.setViewportView(escolherPiloto);
        escolherPiloto.getColumnModel().getSelectionModel().setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);

        escolherCarro.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Carro ID", "Equipe"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        escolherCarro.getTableHeader().setReorderingAllowed(false);
        jScrollPane3.setViewportView(escolherCarro);

        jLabel28.setText("Primeiro clique em \"Criar\" para cadastrar uma corrida.");

        javax.swing.GroupLayout jpCriarCorridaLayout = new javax.swing.GroupLayout(jpCriarCorrida);
        jpCriarCorrida.setLayout(jpCriarCorridaLayout);
        jpCriarCorridaLayout.setHorizontalGroup(
            jpCriarCorridaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpCriarCorridaLayout.createSequentialGroup()
                .addGroup(jpCriarCorridaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jpCriarCorridaLayout.createSequentialGroup()
                        .addGap(693, 693, 693)
                        .addComponent(jLabel15))
                    .addGroup(jpCriarCorridaLayout.createSequentialGroup()
                        .addGap(85, 85, 85)
                        .addGroup(jpCriarCorridaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jpCriarCorridaLayout.createSequentialGroup()
                                .addComponent(jLabel17)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jLabel28))
                            .addGroup(jpCriarCorridaLayout.createSequentialGroup()
                                .addGroup(jpCriarCorridaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel20)
                                    .addComponent(jLabel13)
                                    .addComponent(jLabel21))
                                .addGap(18, 18, 18)
                                .addGroup(jpCriarCorridaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(voltasCorrida, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(voltasQualificacao, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(jpCriarCorridaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addGroup(jpCriarCorridaLayout.createSequentialGroup()
                                    .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 322, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addGroup(jpCriarCorridaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addComponent(confirmarPiloto)
                                        .addComponent(criarCorrida, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGap(6, 6, 6))
                                .addComponent(jLabel22)))))
                .addContainerGap(128, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jpCriarCorridaLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jLabel14)
                .addGap(288, 288, 288))
        );
        jpCriarCorridaLayout.setVerticalGroup(
            jpCriarCorridaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpCriarCorridaLayout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addComponent(jLabel14)
                .addGap(27, 27, 27)
                .addComponent(jLabel20)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jpCriarCorridaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel13, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(voltasCorrida, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jpCriarCorridaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel21)
                    .addComponent(voltasQualificacao, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jpCriarCorridaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel17)
                    .addComponent(jLabel28))
                .addGap(3, 3, 3)
                .addComponent(jLabel22)
                .addGap(12, 12, 12)
                .addGroup(jpCriarCorridaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane5, javax.swing.GroupLayout.DEFAULT_SIZE, 341, Short.MAX_VALUE)
                    .addGroup(jpCriarCorridaLayout.createSequentialGroup()
                        .addComponent(confirmarPiloto, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(criarCorrida, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 8, Short.MAX_VALUE)
                .addComponent(jLabel15)
                .addGap(59, 59, 59))
        );

        JpPrincipal.add(jpCriarCorrida, "Cadastrar corrida");

        jLabel16.setFont(new java.awt.Font("Ubuntu", 1, 36)); // NOI18N
        jLabel16.setText("Rank de pilotos");

        jRank.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Rank", "Nome", "Data", "Volta mais rápida"
            }
        ));
        jScrollPane2.setViewportView(jRank);
        if (jRank.getColumnModel().getColumnCount() > 0) {
            jRank.getColumnModel().getColumn(0).setMinWidth(5);
            jRank.getColumnModel().getColumn(0).setMaxWidth(70);
        }

        javax.swing.GroupLayout JpRankLayout = new javax.swing.GroupLayout(JpRank);
        JpRank.setLayout(JpRankLayout);
        JpRankLayout.setHorizontalGroup(
            JpRankLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(JpRankLayout.createSequentialGroup()
                .addContainerGap(41, Short.MAX_VALUE)
                .addGroup(JpRankLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, JpRankLayout.createSequentialGroup()
                        .addComponent(jLabel16)
                        .addGap(311, 311, 311))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, JpRankLayout.createSequentialGroup()
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 657, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(123, 123, 123))))
        );
        JpRankLayout.setVerticalGroup(
            JpRankLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(JpRankLayout.createSequentialGroup()
                .addGap(46, 46, 46)
                .addComponent(jLabel16)
                .addGap(33, 33, 33)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 320, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(268, Short.MAX_VALUE))
        );

        JpPrincipal.add(JpRank, "Rank de pilotos");

        jLabel18.setFont(new java.awt.Font("Ubuntu", 1, 36)); // NOI18N
        jLabel18.setText("Gerenciar Corrida");

        comecarCorrida.setText("Começar");
        comecarCorrida.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comecarCorridaActionPerformed(evt);
            }
        });

        pausarCorrida.setText("Pausar");
        pausarCorrida.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pausarCorridaActionPerformed(evt);
            }
        });

        reiniciarCorrida.setText("Reiniciar");
        reiniciarCorrida.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                reiniciarCorridaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout JpgerenciarCorridaLayout = new javax.swing.GroupLayout(JpgerenciarCorrida);
        JpgerenciarCorrida.setLayout(JpgerenciarCorridaLayout);
        JpgerenciarCorridaLayout.setHorizontalGroup(
            JpgerenciarCorridaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(JpgerenciarCorridaLayout.createSequentialGroup()
                .addGroup(JpgerenciarCorridaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(JpgerenciarCorridaLayout.createSequentialGroup()
                        .addGap(236, 236, 236)
                        .addComponent(jLabel18))
                    .addGroup(JpgerenciarCorridaLayout.createSequentialGroup()
                        .addGap(297, 297, 297)
                        .addGroup(JpgerenciarCorridaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(pausarCorrida, javax.swing.GroupLayout.PREFERRED_SIZE, 192, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(comecarCorrida, javax.swing.GroupLayout.PREFERRED_SIZE, 192, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(reiniciarCorrida, javax.swing.GroupLayout.PREFERRED_SIZE, 185, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(281, Short.MAX_VALUE))
        );
        JpgerenciarCorridaLayout.setVerticalGroup(
            JpgerenciarCorridaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(JpgerenciarCorridaLayout.createSequentialGroup()
                .addGap(43, 43, 43)
                .addComponent(jLabel18)
                .addGap(39, 39, 39)
                .addComponent(comecarCorrida, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(56, 56, 56)
                .addComponent(pausarCorrida, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(74, 74, 74)
                .addComponent(reiniciarCorrida, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(177, Short.MAX_VALUE))
        );

        JpPrincipal.add(JpgerenciarCorrida, "Gerenciar Corrida");

        verPilotosCadastrados.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Nome", "Volta mais rápida"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        verPilotosCadastrados.getTableHeader().setReorderingAllowed(false);
        jScrollPane4.setViewportView(verPilotosCadastrados);

        jLabel19.setFont(new java.awt.Font("Ubuntu", 1, 36)); // NOI18N
        jLabel19.setText("Pilotos Cadastrados");

        javax.swing.GroupLayout pilotosCadLayout = new javax.swing.GroupLayout(pilotosCad);
        pilotosCad.setLayout(pilotosCadLayout);
        pilotosCadLayout.setHorizontalGroup(
            pilotosCadLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pilotosCadLayout.createSequentialGroup()
                .addContainerGap(71, Short.MAX_VALUE)
                .addGroup(pilotosCadLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pilotosCadLayout.createSequentialGroup()
                        .addComponent(jLabel19)
                        .addGap(273, 273, 273))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pilotosCadLayout.createSequentialGroup()
                        .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 633, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(117, 117, 117))))
        );
        pilotosCadLayout.setVerticalGroup(
            pilotosCadLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pilotosCadLayout.createSequentialGroup()
                .addGap(53, 53, 53)
                .addComponent(jLabel19)
                .addGap(44, 44, 44)
                .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(152, Short.MAX_VALUE))
        );

        JpPrincipal.add(pilotosCad, "Pilotos Cadastrados");

        menuPrincipal.setMaximumSize(new java.awt.Dimension(120, 32769));
        menuPrincipal.setMinimumSize(new java.awt.Dimension(120, 15));

        jMenu1.setText("Cadastro");

        cadAdm.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/user_adm.png"))); // NOI18N
        cadAdm.setText("Administrador");
        cadAdm.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cadAdmActionPerformed(evt);
            }
        });
        jMenu1.add(cadAdm);

        CadCarro.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/car_add.png"))); // NOI18N
        CadCarro.setText("Carro");
        CadCarro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CadCarroActionPerformed(evt);
            }
        });
        jMenu1.add(CadCarro);

        cadPiloto.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/user_piloto.png"))); // NOI18N
        cadPiloto.setText("Piloto");
        cadPiloto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cadPilotoActionPerformed(evt);
            }
        });
        jMenu1.add(cadPiloto);

        menuPrincipal.add(jMenu1);

        pilotosCadastrados.setText("Corrida");

        cadCorrida.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/flag_red.png"))); // NOI18N
        cadCorrida.setText("Criar corrida");
        cadCorrida.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cadCorridaActionPerformed(evt);
            }
        });
        pilotosCadastrados.add(cadCorrida);

        gerenciarRace.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/cog_go.png"))); // NOI18N
        gerenciarRace.setText("Gerenciar corrida");
        gerenciarRace.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                gerenciarRaceActionPerformed(evt);
            }
        });
        pilotosCadastrados.add(gerenciarRace);

        pilotosRegisters.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/joystick_add.png"))); // NOI18N
        pilotosRegisters.setText("Pilotos cadastrados");
        pilotosRegisters.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pilotosRegistersActionPerformed(evt);
            }
        });
        pilotosCadastrados.add(pilotosRegisters);

        menuPrincipal.add(pilotosCadastrados);

        jMenu4.setText("Remover");

        removePiloto.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/user_delete.png"))); // NOI18N
        removePiloto.setText("Piloto");
        removePiloto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                removePilotoActionPerformed(evt);
            }
        });
        jMenu4.add(removePiloto);

        removeCarro.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/car_delete.png"))); // NOI18N
        removeCarro.setText("Carro");
        removeCarro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                removeCarroActionPerformed(evt);
            }
        });
        jMenu4.add(removeCarro);

        menuPrincipal.add(jMenu4);

        rank.setText("Rank");

        visualizarRank.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/flag_yellow.png"))); // NOI18N
        visualizarRank.setText("Visualizar Rank");
        visualizarRank.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                visualizarRankActionPerformed(evt);
            }
        });
        rank.add(visualizarRank);

        menuPrincipal.add(rank);

        outrasOpcoes.setText("Outras..");
        outrasOpcoes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                outrasOpcoesActionPerformed(evt);
            }
        });

        home_page.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/application_home.png"))); // NOI18N
        home_page.setText("Início");
        home_page.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                home_pageActionPerformed(evt);
            }
        });
        outrasOpcoes.add(home_page);

        logout.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/door_out.png"))); // NOI18N
        logout.setText("Sair");
        logout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                logoutActionPerformed(evt);
            }
        });
        outrasOpcoes.add(logout);

        menuPrincipal.add(outrasOpcoes);

        setJMenuBar(menuPrincipal);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(0, 59, Short.MAX_VALUE)
                .addComponent(JpPrincipal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 59, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(JpPrincipal, javax.swing.GroupLayout.PREFERRED_SIZE, 710, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(27, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    /*
        MÉTODOS QUE CHAMAM AS TELAS PARA SEREM VISUALIZADAS E OUTROS MÉTODOS REPONSÃVEIS PELAS AÇÕES DOS BUTÕES
    */
    /**
     * Método que exibit a tela de cadastro de adm.
     * @param evt 
     */
    private void cadAdmActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cadAdmActionPerformed
        CardLayout cl = (CardLayout) JpPrincipal.getLayout();
        cl.show(JpPrincipal, "Cadastro de novo Administrador");      
    }//GEN-LAST:event_cadAdmActionPerformed

    /**
     * Método que exibi tela de cadastro carro.
     * @param evt 
     */
    private void CadCarroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CadCarroActionPerformed
        CardLayout cl = (CardLayout) JpPrincipal.getLayout();
        cl.show(JpPrincipal, "Cadastro de novo Carro");
        idCarro.setText(null);
        //envia um pacote requerindo a leitura do sensor para um cadastro do carro.
        rede.enviarDado(adm.getCliente() , "" ,"10");
    }//GEN-LAST:event_CadCarroActionPerformed

    private void outrasOpcoesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_outrasOpcoesActionPerformed
  
    }//GEN-LAST:event_outrasOpcoesActionPerformed

    /**
     * Método que exibi tela de cadastro de piloto.
     * @param evt 
     */
    private void cadPilotoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cadPilotoActionPerformed
        CardLayout cl = (CardLayout) JpPrincipal.getLayout();
        cl.show(JpPrincipal, "Cadastro de Piloto");
    }//GEN-LAST:event_cadPilotoActionPerformed

    /**
     * Método que exibi tela inicial do adm.
     * @param evt 
     */
    private void home_pageActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_home_pageActionPerformed
         CardLayout cl = (CardLayout) JpPrincipal.getLayout();
         cl.show(JpPrincipal, "home");
    }//GEN-LAST:event_home_pageActionPerformed

    /**
     * Método responsável por remover um carro que está cadastrado.
     * @param evt 
     */
    private void removeCarroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_removeCarroActionPerformed
        CardLayout cl = (CardLayout) JpPrincipal.getLayout();
        cl.show(JpPrincipal, "Remover carro");
        
        List<Carro> carrosCadastrados    = gerenciador.getCarros();
        DefaultTableModel  mostrarCarros = (DefaultTableModel) removeCar.getModel();
        gerenciador.limpaTabela(removeCar);
        synchronized(carrosCadastrados){
            //iterador para percorrer a lista e mostrar os carros cadastrados
            for (Iterator<Carro> it = carrosCadastrados.iterator(); it.hasNext();) {
                Carro car = it.next();
                Object[] dados = {car.getId(), car.getEquipe(), car.getNumero()};
                mostrarCarros.addRow(dados); //adiciona nova linha na tabela de carros cadastrados.
            }
        }
    }//GEN-LAST:event_removeCarroActionPerformed

    /**
     * Método que exibit tela de remover piloto.
     * @param evt 
     */
    private void removePilotoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_removePilotoActionPerformed
       CardLayout cl = (CardLayout) JpPrincipal.getLayout();
       cl.show(JpPrincipal, "Remover piloto");
    }//GEN-LAST:event_removePilotoActionPerformed

    /**
     * Método que exibi tela de criar corrida, exibi os pilotos e carros cadastrado no sistema e pega
     * os dados escritos e envia aos controllers para o devido tratamento.
     * @param evt 
     */
    private void cadCorridaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cadCorridaActionPerformed
        CardLayout cl = (CardLayout) JpPrincipal.getLayout();
        cl.show(JpPrincipal, "Cadastrar corrida");
        
        List<Carro> carrosCadastrados    = gerenciador.getCarros(); //lista de carros cadastrados
        DefaultTableModel  mostrar = (DefaultTableModel) escolherCarro.getModel();
        gerenciador.limpaTabela(escolherCarro); //limpa a tabela de carros disṕoníveis com o objetivo de atualizar
        synchronized(carrosCadastrados){
            //iterador para percorrer a lista e mostrar os carros cadastrados
            for (Iterator<Carro> it = carrosCadastrados.iterator(); it.hasNext();) {
                Carro car = it.next();
                Object[] dados = {car.getId(), car.getEquipe()};
                mostrar.addRow(dados); //adiciona nova linha na tabela de carros para associar com um piloto.
            }
        }
        
        mostrar = (DefaultTableModel) escolherPiloto.getModel();
        List<Piloto> pilotosCadastrados = gerenciador.getPilotos();  //lista de pilotos cadastrados
        gerenciador.limpaTabela(escolherPiloto); //limpa a tabela de pilotos com  o objetivo de atualizar
        synchronized(pilotosCadastrados){
            //iterador para percorrer a lista e mostrar os pilotos cadastrados
            for (Iterator<Piloto> it = pilotosCadastrados.iterator(); it.hasNext();) {
                Piloto piloto = it.next();
               
                if(piloto.getRecord() == null){
                    Object[] dados = {piloto.getNome(),"sem valor por enquanto"};
                    mostrar.addRow(dados); //adiciona nova linha na tabela de pilotos para escolher.
                }else{
                    Object[] dados = {piloto.getNome(),piloto.getRecord().getTempo()};
                    mostrar.addRow(dados); //adiciona nova linha na tabela de pilotos para escolher.
                }
            }
        }       
    }//GEN-LAST:event_cadCorridaActionPerformed

    /**
     * Método que exibi tela de rank de pilotos.
     * @param evt 
     */
    private void visualizarRankActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_visualizarRankActionPerformed
        CardLayout cl = (CardLayout) JpPrincipal.getLayout();
        cl.show(JpPrincipal, "Rank de pilotos");
        List<Piloto> pilotosCadastrados = gerenciador.getPilotos();
        DefaultTableModel  mostrarPilotos = (DefaultTableModel) jRank.getModel();
        synchronized(pilotosCadastrados){
            Collections.sort(pilotosCadastrados);
            int i = 1;
            //iterador para percorrer a lista e mostrar os pilotos cadastrados
            for (Iterator<Piloto> it = pilotosCadastrados.iterator(); it.hasNext();) {
                Piloto piloto = it.next();
                if(piloto.getRecord() == null){
                    Object[] dados = {i , piloto.getNome(),"sem valor por enquanto" ,"sem valor por enquanto" };
                    mostrarPilotos.addRow(dados); //adiciona nova linha na tabela de pilotos cadastrados.
                }else{
                    Object[] dados = {i , piloto.getNome(),piloto.getRecord().getData() , piloto.getRecord().getTempo()};
                    mostrarPilotos.addRow(dados); //adiciona nova linha na tabela de pilotos cadastrados.
                }
                i++;
            }
        }
    }//GEN-LAST:event_visualizarRankActionPerformed

    /**
     * Método que exibi tela de gerenciar um corrida.
     * @param evt 
     */
    private void gerenciarRaceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_gerenciarRaceActionPerformed
        CardLayout cl = (CardLayout) JpPrincipal.getLayout();
        cl.show(JpPrincipal, "Gerenciar Corrida");
    }//GEN-LAST:event_gerenciarRaceActionPerformed

    /**
     * Método que exibi todos os pilotos cadastrados no sistema.
     * @param evt 
     */
    private void pilotosRegistersActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pilotosRegistersActionPerformed
        CardLayout cl = (CardLayout) JpPrincipal.getLayout();
        cl.show(JpPrincipal, "Pilotos Cadastrados");
        List<Piloto> pilotosCadastrados = gerenciador.getPilotos();
        DefaultTableModel  mostrarPilotos = (DefaultTableModel) verPilotosCadastrados.getModel();
        gerenciador.limpaTabela(verPilotosCadastrados);
        synchronized(pilotosCadastrados){
            //iterador para percorrer a lista e mostrar os pilotos cadastrados
            for (Iterator<Piloto> it = pilotosCadastrados.iterator(); it.hasNext();) {
                Piloto piloto = it.next();
               
                if(piloto.getRecord() == null){
                    Object[] dados = {piloto.getNome(),"sem valor por enquanto"};
                    mostrarPilotos.addRow(dados); //adiciona nova linha na tabela de pilotos cadastrados.
                }else{
                    Object[] dados = {piloto.getNome(),piloto.getRecord().getTempo()};
                    mostrarPilotos.addRow(dados); //adiciona nova linha na tabela de pilotos cadastrados.
                }
            }
        }
    }//GEN-LAST:event_pilotosRegistersActionPerformed

    /**
     * Método que envia um pacote ao servidor para salvar um novo adm no sistema.
     * @param evt 
     */
    private void salvarAdmActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_salvarAdmActionPerformed
        String nome  = nomeAdm.getText();
        String senha = new String(senhaAdm.getPassword()).trim();
        if(!gerenciador.existeAdm(nome,senha)){
            //envia para o servidor realizar o cadastrado no sistema
            rede.enviarDado(adm.getCliente() , gerenciador.cadastrarAdministrador(nome ,senha).toString() ,"13");
        }else{
            //rejeita os dados caso o adm já tenha sido cadastrado
            JOptionPane.showMessageDialog(null,"Administrador já cadastrado. Por favor, tente outro!");
        }
    }//GEN-LAST:event_salvarAdmActionPerformed

    /**
     * Método que envia um pacote ao servidor para salvar um novo carro no sistema.
     * @param evt 
     */
    private void salvarCarroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_salvarCarroActionPerformed
        String id     = idCarro.getText();
        String equipe = equipeCarro.getText();
        String numero = numeroCarro.getText();
        if(!gerenciador.existeCarro(id)){
            rede.enviarDado(adm.getCliente() , gerenciador.cadastrarCarro(id, equipe, numero).toString() , "11");
        }else{
            //rejeita os dados caso o carro já tenha sido cadastrado
            JOptionPane.showMessageDialog(null,"Este carro já está cadastrado. Por favor, tente outro!");
        }
    }//GEN-LAST:event_salvarCarroActionPerformed

    /**
     * Método que envia um pacote ao servidor para salvar um novo piloto no sistema.
     * @param evt 
     */
    private void salvarPilotoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_salvarPilotoActionPerformed
        String nome = nomePiloto.getText();
        if(!gerenciador.existePiloto(nome)){
            rede.enviarDado(adm.getCliente() , gerenciador.cadastrarPiloto(nome).toString() , "12");
        }else{
            //rejeita os dados caso o carro já tenha sido cadastrado
            JOptionPane.showMessageDialog(null,"Este piloto já está cadastrado. Por favor, tente outro!");
        }
    }//GEN-LAST:event_salvarPilotoActionPerformed

    /**
     * Método que envia um pacote ao servidor para remover um piloto do sistema.
     * @param evt 
     */
    private void removerPilotoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_removerPilotoActionPerformed
        String piloto = pilotoRemover.getText();
        if(gerenciador.existePiloto(piloto)){
            rede.enviarDado(adm.getCliente() , gerenciador.piloto(piloto).toString() , "21");
            gerenciador.removerPiloto(piloto);
            JOptionPane.showMessageDialog(null,"Piloto removido com sucesso!");
        }else{
            JOptionPane.showMessageDialog(null,"Este piloto não está cadastrado, ou campo nome não está preenchido corretamente!");
        }
    }//GEN-LAST:event_removerPilotoActionPerformed
    
    /**
     * Método para realizar logout do cliente.
     * @param evt 
     */
    private void logoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_logoutActionPerformed
        rede.enviarDado(adm.getCliente(), "", "00"); //pacote para informar ao servidor que o cliente está sendo desconectado
        try {
            adm.fecharConexão();
            JOptionPane.showMessageDialog(null,"Logout com sucesso!");
        } catch (IOException ex) {
            JOptionPane.showMessageDialog(null,"Erro ao desconectar!");
        }
    }//GEN-LAST:event_logoutActionPerformed
    /**
     * Método que envia um pacote ao servidor para remover um carro do sistema.
     * @param evt 
     */
    private void removerCarroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_removerCarroActionPerformed
        if(removeCar.getSelectedRow() != -1){
            String carroId = removeCar.getValueAt(removeCar.getSelectedRow(),0).toString(); //pega a linha do carro selecionado na tabela
            rede.enviarDado(adm.getCliente() , gerenciador.carro(carroId).toString() , "22"); //enviar pacote para o servidor informando que um carro será excluído
            
            //remove a linha da tabela
            DefaultTableModel remove = (DefaultTableModel) removeCar.getModel();
            remove.removeRow(removeCar.getSelectedRow());
        }else{
           JOptionPane.showMessageDialog(null,"Selecione um carro!");
        }     
    }//GEN-LAST:event_removerCarroActionPerformed

    /**
     * Método que confirma a associação entre um carro e um piloto para uma corrida ou qualificação.
     * @param evt 
     */
    private void confirmarPilotoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_confirmarPilotoActionPerformed
        if(!corrida.isNull()){ //se já tiver uma corrida cadastrada
            if(( escolherPiloto.getSelectedRow() != -1) && (escolherCarro.getSelectedRow() != -1)){//verifica se alguma linha das tabelas foram selecionadas
                String nome     = escolherPiloto.getValueAt(escolherPiloto.getSelectedRow(), 0).toString(); //pega Nome do piloto
                String carroId  = escolherCarro.getValueAt(escolherCarro.getSelectedRow(), 0).toString(); //pega coluna Carro ID
            
                Carro pilotoCarro = corrida.cadastraCompetidor(gerenciador.carro(carroId), gerenciador.piloto(nome));
                if(pilotoCarro != null){
                    rede.enviarDado(adm.getCliente(),pilotoCarro.toString(),"32"); //envia para o servidor o piloto associado ao carro
                    JOptionPane.showMessageDialog(null,"Associação Confirmada!");
                }else{
                    JOptionPane.showMessageDialog(null,"O carro ou piloto selecionado já estão na corrida!");
                }
            }else{
                JOptionPane.showMessageDialog(null,"Associe um piloto a um carro!");
            }
        }else{
            JOptionPane.showMessageDialog(null,"Desculpe, mas não existe corrida cadastrada.");
        }
    }//GEN-LAST:event_confirmarPilotoActionPerformed

    /**
     * Método para a criação de uma nova corrida enviando o número de voltas desejada para a corrida
     * e o evento de qualificação.
     * @param evt 
     */
    private void criarCorridaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_criarCorridaActionPerformed
        int voltasRace   = gerenciador.strToInt(voltasCorrida.getText(),0);
        int qualificacao = gerenciador.strToInt(voltasQualificacao.getText(),0);
        if( (qualificacao == 0) || (voltasRace == 0) ){
            JOptionPane.showMessageDialog(null,"Preencha os campos de volta!" );
        }else{
            if(corrida.isNull()){//verifica se já existe uma corrida cadastrada no sistema
                //envio de cadastro de uma corrida
                rede.enviarDado(adm.getCliente() , corrida.cadastrarCorrida(voltasRace).toString() , "30");
                JOptionPane.showMessageDialog(null,"Corrida criada com sucesso!");
                //falta enviar voltas da qualificação
            }else{
                JOptionPane.showMessageDialog(null,"Desculpe, mas já existe uma corrida cadastrada! Espere encerrar.");
            }
        }

    }//GEN-LAST:event_criarCorridaActionPerformed

    /**
     * Método que envia um sinal para o ínicio de uma corrida.
     * @param evt 
     */
    private void comecarCorridaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comecarCorridaActionPerformed
        if(corrida.isNull()){
            JOptionPane.showMessageDialog(null,"Desculpe, mas não existe corrida cadastrada.");
        }else{
            rede.enviarDado(adm.getCliente(), "", "31");
        }
    }//GEN-LAST:event_comecarCorridaActionPerformed

    /**
     * Método que envia um pacote para pausar uma corrida.
     * @param evt 
     */
    private void pausarCorridaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pausarCorridaActionPerformed
        if(corrida.isNull()){
            JOptionPane.showMessageDialog(null,"Desculpe, mas não existe corrida cadastrada.");
        }else{
            rede.enviarDado(adm.getCliente(), "", "33");
        }
    }//GEN-LAST:event_pausarCorridaActionPerformed

    /**
     * Método que envia um pacote para reiniciar uma corrida.
     * @param evt 
     */
    private void reiniciarCorridaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_reiniciarCorridaActionPerformed
        if(corrida.isNull()){
            JOptionPane.showMessageDialog(null,"Desculpe, mas não existe corrida cadastrada.");
        }else{
            rede.enviarDado(adm.getCliente(), "", "34");
        }
    }//GEN-LAST:event_reiniciarCorridaActionPerformed

    /**Método que efetua um login do administrador.
     * @param evt 
     */
    private void loginAdmActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_loginAdmActionPerformed
        String nomeAdm  = userAdmLogin.getText();
        String senhaAdm = new String( senhaAdmLogin.getPassword()).trim();
        if(gerenciador.existeAdm(nomeAdm, senhaAdm)){
            JOptionPane.showMessageDialog(null,"Login feito com sucesso");
            CardLayout cl = (CardLayout) JpPrincipal.getLayout();
            cl.show(JpPrincipal, "home");
            mostrarMenuPrincipal(true); //inicia o menu principal
        }else{
            JOptionPane.showMessageDialog(null,"Desculpe, mas este Adm não está cadastrado.");
        }
    }//GEN-LAST:event_loginAdmActionPerformed

    /**
     * Método para escrever na interface o ID do carro que será cadastrado no sistema.
     * @param evt 
     */
    private void pegarIDCarroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pegarIDCarroActionPerformed
        if(ControllerGerenciador.getIdCarroCad() != null){
            idCarro.setText(ControllerGerenciador.getIdCarroCad());
            ControllerGerenciador.setIdCarroCad(null);
        }else{
            JOptionPane.showMessageDialog(null,"ID ainda não disponível!!");
        }
    }//GEN-LAST:event_pegarIDCarroActionPerformed

    /*
        FIM DOS MÉTODOS QUE CHAMAM AS TELAS PARA SEREM VISUALIZADAS E OUTROS MÉTODOS REPONSÃVEIS PELAS AÇÕES DOS BUTÕES
    */
    ///////////////////////////////////////////////////////////////////////////////////////////////////////////////////
    /**
     * Método que habilita ou desabilita o menu principal do administrador.
     * @param mostrar 
     */
    public void mostrarMenuPrincipal(boolean mostrar){
        menuPrincipal.setVisible(mostrar);
    }
    
    /**
     * Método que conecta o cliente administrador ao servidor.
     * @throws IOException 
     */
    public void conectarCliente() throws IOException{
        adm = new Cliente("192.168.25.4" , 12345); 
        adm.executa(); //conecta o cliente ADM ao servidor
        //envia requisição pro servidor para atualizar os dados
        rede.enviarDado(adm.getCliente() , "" ,"100");
    }

    /**
     * @param args the command line arguments
     * @throws java.io.IOException
     */
    public static void main(String args[]) throws IOException {
       
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                try { 
                    new TelaPrincipal().setVisible(true);
                } catch (IOException ex) {
                   JOptionPane.showMessageDialog(null,"Desculpe, erro ao conectar com o servidor!!");
                }
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem CadCarro;
    private javax.swing.JPanel JpHome;
    private javax.swing.JPanel JpPiloto;
    private javax.swing.JPanel JpPrincipal;
    private javax.swing.JPanel JpRank;
    private javax.swing.JPanel JpRemoveCar;
    private javax.swing.JPanel JpgerenciarCorrida;
    private javax.swing.JMenuItem cadAdm;
    private javax.swing.JMenuItem cadCorrida;
    private javax.swing.JMenuItem cadPiloto;
    private javax.swing.JButton comecarCorrida;
    private javax.swing.JButton confirmarPiloto;
    private javax.swing.JButton criarCorrida;
    private javax.swing.JTextField equipeCarro;
    private javax.swing.JTable escolherCarro;
    private javax.swing.JTable escolherPiloto;
    private javax.swing.JMenuItem gerenciarRace;
    private javax.swing.JMenuItem home_page;
    private javax.swing.JTextField idCarro;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel32;
    private javax.swing.JLabel jLabel33;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JTable jRank;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JPanel jpCadAdm;
    private javax.swing.JPanel jpCardCarro;
    private javax.swing.JPanel jpCriarCorrida;
    private javax.swing.JPanel jpRemoverPiloto;
    private javax.swing.JButton loginAdm;
    private javax.swing.JMenuItem logout;
    private javax.swing.JMenuBar menuPrincipal;
    private javax.swing.JTextField nomeAdm;
    private javax.swing.JTextField nomePiloto;
    private javax.swing.JTextField numeroCarro;
    private javax.swing.JMenu outrasOpcoes;
    private javax.swing.JButton pausarCorrida;
    private javax.swing.JButton pegarIDCarro;
    private javax.swing.JTextField pilotoRemover;
    private javax.swing.JPanel pilotosCad;
    private javax.swing.JMenu pilotosCadastrados;
    private javax.swing.JMenuItem pilotosRegisters;
    private javax.swing.JMenu rank;
    private javax.swing.JButton reiniciarCorrida;
    private javax.swing.JTable removeCar;
    private javax.swing.JMenuItem removeCarro;
    private javax.swing.JMenuItem removePiloto;
    private javax.swing.JButton removerCarro;
    private javax.swing.JButton removerPiloto;
    private javax.swing.JButton salvarAdm;
    private javax.swing.JButton salvarCarro;
    private javax.swing.JButton salvarPiloto;
    private javax.swing.JPasswordField senhaAdm;
    private javax.swing.JPasswordField senhaAdmLogin;
    private javax.swing.JPanel telaLogin;
    private javax.swing.JTextField userAdmLogin;
    private javax.swing.JTable verPilotosCadastrados;
    private javax.swing.JMenuItem visualizarRank;
    private javax.swing.JTextField voltasCorrida;
    private javax.swing.JTextField voltasQualificacao;
    // End of variables declaration//GEN-END:variables
}
