/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import java.awt.CardLayout;

/**
 *
 * @author lablenda3
 */
public class TelaPrincipal extends javax.swing.JFrame {

    /**
     * Creates new form TelaPrincipal
     */
    public TelaPrincipal() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        JpPrincipal = new javax.swing.JPanel();
        JpHome = new javax.swing.JPanel();
        jpCardCarro = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jTextField2 = new javax.swing.JTextField();
        jTextField3 = new javax.swing.JTextField();
        jTextField4 = new javax.swing.JTextField();
        jButton2 = new javax.swing.JButton();
        jpCadAdm = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jPasswordField1 = new javax.swing.JPasswordField();
        jButton1 = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        JpPiloto = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jTextField5 = new javax.swing.JTextField();
        jButton3 = new javax.swing.JButton();
        JpRemoveCar = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jButton4 = new javax.swing.JButton();
        jLabel10 = new javax.swing.JLabel();
        jpRemoverPiloto = new javax.swing.JPanel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jTextField6 = new javax.swing.JTextField();
        jButton5 = new javax.swing.JButton();
        jpCriarCorrida = new javax.swing.JPanel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jTextField7 = new javax.swing.JTextField();
        jLabel15 = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        cadAdm = new javax.swing.JMenuItem();
        CadCarro = new javax.swing.JMenuItem();
        cadPiloto = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        cadCorrida = new javax.swing.JMenuItem();
        cadCompetidores = new javax.swing.JMenuItem();
        gerenciarRace = new javax.swing.JMenuItem();
        jMenu4 = new javax.swing.JMenu();
        removePiloto = new javax.swing.JMenuItem();
        removeCarro = new javax.swing.JMenuItem();
        outrasOpcoes = new javax.swing.JMenu();
        home_page = new javax.swing.JMenuItem();
        jMenuItem1 = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Cliente Administrador");
        setResizable(false);

        JpPrincipal.setLayout(new java.awt.CardLayout());

        javax.swing.GroupLayout JpHomeLayout = new javax.swing.GroupLayout(JpHome);
        JpHome.setLayout(JpHomeLayout);
        JpHomeLayout.setHorizontalGroup(
            JpHomeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 844, Short.MAX_VALUE)
        );
        JpHomeLayout.setVerticalGroup(
            JpHomeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 693, Short.MAX_VALUE)
        );

        JpPrincipal.add(JpHome, "home");

        jLabel4.setFont(new java.awt.Font("Ubuntu", 1, 36)); // NOI18N
        jLabel4.setText("Cadastro de Carro");

        jLabel5.setFont(new java.awt.Font("Ubuntu", 1, 36)); // NOI18N
        jLabel5.setText("ID:");

        jLabel6.setFont(new java.awt.Font("Ubuntu", 1, 36)); // NOI18N
        jLabel6.setText("Equipe:");

        jLabel7.setFont(new java.awt.Font("Ubuntu", 1, 36)); // NOI18N
        jLabel7.setText("Número:");

        jButton2.setText("Cadastrar");

        javax.swing.GroupLayout jpCardCarroLayout = new javax.swing.GroupLayout(jpCardCarro);
        jpCardCarro.setLayout(jpCardCarroLayout);
        jpCardCarroLayout.setHorizontalGroup(
            jpCardCarroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpCardCarroLayout.createSequentialGroup()
                .addContainerGap(269, Short.MAX_VALUE)
                .addComponent(jLabel4)
                .addGap(264, 264, 264))
            .addGroup(jpCardCarroLayout.createSequentialGroup()
                .addGroup(jpCardCarroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jpCardCarroLayout.createSequentialGroup()
                        .addGap(59, 59, 59)
                        .addGroup(jpCardCarroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jpCardCarroLayout.createSequentialGroup()
                                .addGap(150, 150, 150)
                                .addComponent(jTextField4, javax.swing.GroupLayout.DEFAULT_SIZE, 510, Short.MAX_VALUE))
                            .addGroup(jpCardCarroLayout.createSequentialGroup()
                                .addGroup(jpCardCarroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(jpCardCarroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(jpCardCarroLayout.createSequentialGroup()
                                            .addComponent(jLabel6)
                                            .addGap(4, 4, 4))
                                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jpCardCarroLayout.createSequentialGroup()
                                            .addComponent(jLabel5)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)))
                                    .addGroup(jpCardCarroLayout.createSequentialGroup()
                                        .addComponent(jLabel7)
                                        .addGap(4, 4, 4)))
                                .addGroup(jpCardCarroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jTextField3, javax.swing.GroupLayout.DEFAULT_SIZE, 510, Short.MAX_VALUE)
                                    .addComponent(jTextField2)))))
                    .addGroup(jpCardCarroLayout.createSequentialGroup()
                        .addGap(358, 358, 358)
                        .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jpCardCarroLayout.setVerticalGroup(
            jpCardCarroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpCardCarroLayout.createSequentialGroup()
                .addGap(78, 78, 78)
                .addComponent(jLabel4)
                .addGap(75, 75, 75)
                .addGroup(jpCardCarroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5))
                .addGap(47, 47, 47)
                .addGroup(jpCardCarroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(jTextField3, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(67, 67, 67)
                .addGroup(jpCardCarroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(jTextField4, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(47, 47, 47)
                .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(144, Short.MAX_VALUE))
        );

        JpPrincipal.add(jpCardCarro, "Cadastro de novo Carro");

        jpCadAdm.setBackground(new java.awt.Color(250, 255, 255));

        jLabel1.setFont(new java.awt.Font("Ubuntu", 1, 36)); // NOI18N
        jLabel1.setText("Nome:");

        jLabel2.setFont(new java.awt.Font("Ubuntu", 1, 36)); // NOI18N
        jLabel2.setText("Senha:");

        jPasswordField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jPasswordField1ActionPerformed(evt);
            }
        });

        jButton1.setText("Salvar");

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/cadAdm.png"))); // NOI18N

        javax.swing.GroupLayout jpCadAdmLayout = new javax.swing.GroupLayout(jpCadAdm);
        jpCadAdm.setLayout(jpCadAdmLayout);
        jpCadAdmLayout.setHorizontalGroup(
            jpCadAdmLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpCadAdmLayout.createSequentialGroup()
                .addGroup(jpCadAdmLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jpCadAdmLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addGroup(jpCadAdmLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jpCadAdmLayout.createSequentialGroup()
                                .addGap(65, 65, 65)
                                .addGroup(jpCadAdmLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jpCadAdmLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addComponent(jLabel2)
                                        .addComponent(jLabel1))
                                    .addGroup(jpCadAdmLayout.createSequentialGroup()
                                        .addGap(3, 3, 3)
                                        .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 589, javax.swing.GroupLayout.PREFERRED_SIZE))))
                            .addGroup(jpCadAdmLayout.createSequentialGroup()
                                .addGap(353, 353, 353)
                                .addComponent(jLabel3)))
                        .addComponent(jPasswordField1, javax.swing.GroupLayout.PREFERRED_SIZE, 592, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jpCadAdmLayout.createSequentialGroup()
                        .addGap(65, 65, 65)
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(187, Short.MAX_VALUE))
        );
        jpCadAdmLayout.setVerticalGroup(
            jpCadAdmLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpCadAdmLayout.createSequentialGroup()
                .addGap(64, 64, 64)
                .addComponent(jLabel3)
                .addGap(56, 56, 56)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(35, 35, 35)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPasswordField1, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(35, 35, 35)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(156, Short.MAX_VALUE))
        );

        JpPrincipal.add(jpCadAdm, "Cadastro de novo Administrador");

        jLabel8.setFont(new java.awt.Font("Ubuntu", 1, 36)); // NOI18N
        jLabel8.setText("Cadastro de Piloto");

        jLabel9.setFont(new java.awt.Font("Ubuntu", 1, 36)); // NOI18N
        jLabel9.setText("Nome:");

        jButton3.setText("Cadastrar");

        javax.swing.GroupLayout JpPilotoLayout = new javax.swing.GroupLayout(JpPiloto);
        JpPiloto.setLayout(JpPilotoLayout);
        JpPilotoLayout.setHorizontalGroup(
            JpPilotoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(JpPilotoLayout.createSequentialGroup()
                .addGroup(JpPilotoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(JpPilotoLayout.createSequentialGroup()
                        .addGap(102, 102, 102)
                        .addComponent(jLabel9)
                        .addGroup(JpPilotoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(JpPilotoLayout.createSequentialGroup()
                                .addGap(38, 38, 38)
                                .addComponent(jLabel8))
                            .addGroup(JpPilotoLayout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jTextField5, javax.swing.GroupLayout.PREFERRED_SIZE, 507, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(JpPilotoLayout.createSequentialGroup()
                        .addGap(348, 348, 348)
                        .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(113, Short.MAX_VALUE))
        );
        JpPilotoLayout.setVerticalGroup(
            JpPilotoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(JpPilotoLayout.createSequentialGroup()
                .addGap(68, 68, 68)
                .addGroup(JpPilotoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel9)
                    .addGroup(JpPilotoLayout.createSequentialGroup()
                        .addComponent(jLabel8)
                        .addGap(75, 75, 75)
                        .addComponent(jTextField5, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(46, 46, 46)
                .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(372, Short.MAX_VALUE))
        );

        JpPrincipal.add(JpPiloto, "Cadastro de Piloto");

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "Equipe", "Número"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        jButton4.setText("Remover");

        jLabel10.setFont(new java.awt.Font("Ubuntu", 1, 36)); // NOI18N
        jLabel10.setText("Remover Carro");

        javax.swing.GroupLayout JpRemoveCarLayout = new javax.swing.GroupLayout(JpRemoveCar);
        JpRemoveCar.setLayout(JpRemoveCarLayout);
        JpRemoveCarLayout.setHorizontalGroup(
            JpRemoveCarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(JpRemoveCarLayout.createSequentialGroup()
                .addGroup(JpRemoveCarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(JpRemoveCarLayout.createSequentialGroup()
                        .addGap(291, 291, 291)
                        .addComponent(jLabel10))
                    .addGroup(JpRemoveCarLayout.createSequentialGroup()
                        .addGap(82, 82, 82)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 678, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(JpRemoveCarLayout.createSequentialGroup()
                        .addGap(367, 367, 367)
                        .addComponent(jButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(84, Short.MAX_VALUE))
        );
        JpRemoveCarLayout.setVerticalGroup(
            JpRemoveCarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(JpRemoveCarLayout.createSequentialGroup()
                .addContainerGap(65, Short.MAX_VALUE)
                .addComponent(jLabel10)
                .addGap(34, 34, 34)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(62, 62, 62))
        );

        JpPrincipal.add(JpRemoveCar, "Remover carro");

        jLabel11.setFont(new java.awt.Font("Ubuntu", 1, 36)); // NOI18N
        jLabel11.setText("Remover Piloto");

        jLabel12.setFont(new java.awt.Font("Ubuntu", 1, 36)); // NOI18N
        jLabel12.setText("Nome:");

        jButton5.setText("Remover");

        javax.swing.GroupLayout jpRemoverPilotoLayout = new javax.swing.GroupLayout(jpRemoverPiloto);
        jpRemoverPiloto.setLayout(jpRemoverPilotoLayout);
        jpRemoverPilotoLayout.setHorizontalGroup(
            jpRemoverPilotoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpRemoverPilotoLayout.createSequentialGroup()
                .addGroup(jpRemoverPilotoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jpRemoverPilotoLayout.createSequentialGroup()
                        .addGap(284, 284, 284)
                        .addComponent(jLabel11))
                    .addGroup(jpRemoverPilotoLayout.createSequentialGroup()
                        .addGap(65, 65, 65)
                        .addComponent(jLabel12)
                        .addGap(3, 3, 3)
                        .addComponent(jTextField6, javax.swing.GroupLayout.PREFERRED_SIZE, 495, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jpRemoverPilotoLayout.createSequentialGroup()
                        .addGap(343, 343, 343)
                        .addComponent(jButton5, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(171, Short.MAX_VALUE))
        );
        jpRemoverPilotoLayout.setVerticalGroup(
            jpRemoverPilotoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpRemoverPilotoLayout.createSequentialGroup()
                .addGap(68, 68, 68)
                .addComponent(jLabel11)
                .addGap(81, 81, 81)
                .addGroup(jpRemoverPilotoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel12)
                    .addComponent(jTextField6, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(36, 36, 36)
                .addComponent(jButton5, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(376, Short.MAX_VALUE))
        );

        JpPrincipal.add(jpRemoverPiloto, "Remover piloto");

        jLabel13.setFont(new java.awt.Font("Ubuntu", 1, 24)); // NOI18N
        jLabel13.setText("Quantidade de voltas:");

        jLabel14.setFont(new java.awt.Font("Ubuntu", 1, 36)); // NOI18N
        jLabel14.setText("Criar nova corrida");

        javax.swing.GroupLayout jpCriarCorridaLayout = new javax.swing.GroupLayout(jpCriarCorrida);
        jpCriarCorrida.setLayout(jpCriarCorridaLayout);
        jpCriarCorridaLayout.setHorizontalGroup(
            jpCriarCorridaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpCriarCorridaLayout.createSequentialGroup()
                .addGroup(jpCriarCorridaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jpCriarCorridaLayout.createSequentialGroup()
                        .addGap(252, 252, 252)
                        .addComponent(jLabel14))
                    .addGroup(jpCriarCorridaLayout.createSequentialGroup()
                        .addGap(79, 79, 79)
                        .addComponent(jLabel13)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTextField7, javax.swing.GroupLayout.PREFERRED_SIZE, 402, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jpCriarCorridaLayout.createSequentialGroup()
                        .addGap(541, 541, 541)
                        .addComponent(jLabel15)))
                .addContainerGap(94, Short.MAX_VALUE))
        );
        jpCriarCorridaLayout.setVerticalGroup(
            jpCriarCorridaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpCriarCorridaLayout.createSequentialGroup()
                .addGap(41, 41, 41)
                .addComponent(jLabel14)
                .addGap(39, 39, 39)
                .addGroup(jpCriarCorridaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jpCriarCorridaLayout.createSequentialGroup()
                        .addComponent(jLabel13, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(103, 103, 103))
                    .addGroup(jpCriarCorridaLayout.createSequentialGroup()
                        .addComponent(jTextField7, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addComponent(jLabel15)
                .addContainerGap(439, Short.MAX_VALUE))
        );

        JpPrincipal.add(jpCriarCorrida, "Cadastrar corrida");

        jMenuBar1.setMaximumSize(new java.awt.Dimension(120, 32769));
        jMenuBar1.setMinimumSize(new java.awt.Dimension(120, 15));

        jMenu1.setText("Cadastro");

        cadAdm.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/user_adm.png"))); // NOI18N
        cadAdm.setText("Administrador");
        cadAdm.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cadAdmActionPerformed(evt);
            }
        });
        jMenu1.add(cadAdm);

        CadCarro.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/car_add.png"))); // NOI18N
        CadCarro.setText("Carro");
        CadCarro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CadCarroActionPerformed(evt);
            }
        });
        jMenu1.add(CadCarro);

        cadPiloto.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/user_piloto.png"))); // NOI18N
        cadPiloto.setText("Piloto");
        cadPiloto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cadPilotoActionPerformed(evt);
            }
        });
        jMenu1.add(cadPiloto);

        jMenuBar1.add(jMenu1);

        jMenu2.setText("Corrida");

        cadCorrida.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/flag_red.png"))); // NOI18N
        cadCorrida.setText("Criar corrida");
        cadCorrida.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cadCorridaActionPerformed(evt);
            }
        });
        jMenu2.add(cadCorrida);

        cadCompetidores.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/joystick_add.png"))); // NOI18N
        cadCompetidores.setText("Competidores");
        jMenu2.add(cadCompetidores);

        gerenciarRace.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/cog_go.png"))); // NOI18N
        gerenciarRace.setText("Gerenciar corrida");
        jMenu2.add(gerenciarRace);

        jMenuBar1.add(jMenu2);

        jMenu4.setText("Remover");

        removePiloto.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/user_delete.png"))); // NOI18N
        removePiloto.setText("Piloto");
        removePiloto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                removePilotoActionPerformed(evt);
            }
        });
        jMenu4.add(removePiloto);

        removeCarro.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/car_delete.png"))); // NOI18N
        removeCarro.setText("Carro");
        removeCarro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                removeCarroActionPerformed(evt);
            }
        });
        jMenu4.add(removeCarro);

        jMenuBar1.add(jMenu4);

        outrasOpcoes.setText("Outras..");
        outrasOpcoes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                outrasOpcoesActionPerformed(evt);
            }
        });

        home_page.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/application_home.png"))); // NOI18N
        home_page.setText("Início");
        home_page.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                home_pageActionPerformed(evt);
            }
        });
        outrasOpcoes.add(home_page);

        jMenuItem1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/door_out.png"))); // NOI18N
        jMenuItem1.setText("Sair");
        outrasOpcoes.add(jMenuItem1);

        jMenuBar1.add(outrasOpcoes);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(JpPrincipal, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(JpPrincipal, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void cadAdmActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cadAdmActionPerformed
        CardLayout cl = (CardLayout) JpPrincipal.getLayout();
        cl.show(JpPrincipal, "Cadastro de novo Administrador");
    }//GEN-LAST:event_cadAdmActionPerformed

    private void CadCarroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CadCarroActionPerformed
        CardLayout cl = (CardLayout) JpPrincipal.getLayout();
        cl.show(JpPrincipal, "Cadastro de novo Carro");
    }//GEN-LAST:event_CadCarroActionPerformed

    private void outrasOpcoesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_outrasOpcoesActionPerformed
        
    }//GEN-LAST:event_outrasOpcoesActionPerformed

    private void jPasswordField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jPasswordField1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jPasswordField1ActionPerformed

    private void cadPilotoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cadPilotoActionPerformed
        CardLayout cl = (CardLayout) JpPrincipal.getLayout();
        cl.show(JpPrincipal, "Cadastro de Piloto");
    }//GEN-LAST:event_cadPilotoActionPerformed

    private void home_pageActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_home_pageActionPerformed
         CardLayout cl = (CardLayout) JpPrincipal.getLayout();
         cl.show(JpPrincipal, "home");
    }//GEN-LAST:event_home_pageActionPerformed

    private void removeCarroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_removeCarroActionPerformed
        CardLayout cl = (CardLayout) JpPrincipal.getLayout();
        cl.show(JpPrincipal, "Remover carro");
    }//GEN-LAST:event_removeCarroActionPerformed

    private void removePilotoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_removePilotoActionPerformed
       CardLayout cl = (CardLayout) JpPrincipal.getLayout();
       cl.show(JpPrincipal, "Remover piloto");
    }//GEN-LAST:event_removePilotoActionPerformed

    private void cadCorridaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cadCorridaActionPerformed
        CardLayout cl = (CardLayout) JpPrincipal.getLayout();
        cl.show(JpPrincipal, "Cadastrar corrida");
    }//GEN-LAST:event_cadCorridaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaPrincipal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem CadCarro;
    private javax.swing.JPanel JpHome;
    private javax.swing.JPanel JpPiloto;
    private javax.swing.JPanel JpPrincipal;
    private javax.swing.JPanel JpRemoveCar;
    private javax.swing.JMenuItem cadAdm;
    private javax.swing.JMenuItem cadCompetidores;
    private javax.swing.JMenuItem cadCorrida;
    private javax.swing.JMenuItem cadPiloto;
    private javax.swing.JMenuItem gerenciarRace;
    private javax.swing.JMenuItem home_page;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JPasswordField jPasswordField1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextField jTextField4;
    private javax.swing.JTextField jTextField5;
    private javax.swing.JTextField jTextField6;
    private javax.swing.JTextField jTextField7;
    private javax.swing.JPanel jpCadAdm;
    private javax.swing.JPanel jpCardCarro;
    private javax.swing.JPanel jpCriarCorrida;
    private javax.swing.JPanel jpRemoverPiloto;
    private javax.swing.JMenu outrasOpcoes;
    private javax.swing.JMenuItem removeCarro;
    private javax.swing.JMenuItem removePiloto;
    // End of variables declaration//GEN-END:variables
}
