/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import cliente.Cliente;
import controller.ControllerCorrida;
import controller.ControllerRede;
import java.awt.CardLayout;
import java.io.IOException;
import java.util.logging.Level;
import java.util.logging.Logger;
import model.PainelCorrida;
import model.Qualificacao;

/**
 *
 * @author gabriel
 */
public class ClientRace extends javax.swing.JFrame {
    
    public static ControllerCorrida corrida = null;
    public static ControllerRede rede = null;
    Cliente cliente;
    Qualificacao threadQualificacao;
    PainelCorrida threadCorrida;
    /**
     * Creates new form ClientRace
     */
    public ClientRace() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        JpClienteCorrida = new javax.swing.JPanel();
        JpMenu = new javax.swing.JPanel();
        btnQualificacao = new javax.swing.JButton();
        btnCorrida = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jButtonSairHome = new javax.swing.JButton();
        JpQualificação = new javax.swing.JPanel();
        jLabelQualificacao = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabelRecordQ = new javax.swing.JLabel();
        jLabelAutorQ = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTQualificacao = new javax.swing.JTable();
        JpVoltarQualificação = new javax.swing.JButton();
        jButtonSairQuali = new javax.swing.JButton();
        JpCorrida = new javax.swing.JPanel();
        jLabelCorrida = new javax.swing.JLabel();
        jLabelClass = new javax.swing.JLabel();
        jLabelRecord = new javax.swing.JLabel();
        jLabelAutor = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTCorrida = new javax.swing.JTable();
        btnVoltarCorrida = new javax.swing.JButton();
        jButtonSairClass = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Sessão de Corrida e Qualificação");
        setResizable(false);

        JpClienteCorrida.setLayout(new java.awt.CardLayout());

        JpMenu.setBackground(java.awt.Color.lightGray);
        JpMenu.setBorder(new javax.swing.border.MatteBorder(null));

        btnQualificacao.setText("Qualificação");
        btnQualificacao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnQualificacaoActionPerformed(evt);
            }
        });

        btnCorrida.setText("Corrida");
        btnCorrida.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCorridaActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Ubuntu", 1, 36)); // NOI18N
        jLabel1.setText("Projeto Autorama Inteligente");

        jLabel2.setFont(new java.awt.Font("Ubuntu", 1, 36)); // NOI18N
        jLabel2.setText("M.I Concorrência e Conectividade");

        jButtonSairHome.setText("Sair");
        jButtonSairHome.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSairHomeActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout JpMenuLayout = new javax.swing.GroupLayout(JpMenu);
        JpMenu.setLayout(JpMenuLayout);
        JpMenuLayout.setHorizontalGroup(
            JpMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, JpMenuLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(203, 203, 203))
            .addGroup(JpMenuLayout.createSequentialGroup()
                .addGap(249, 249, 249)
                .addComponent(btnQualificacao, javax.swing.GroupLayout.PREFERRED_SIZE, 171, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(141, 141, 141)
                .addComponent(btnCorrida, javax.swing.GroupLayout.PREFERRED_SIZE, 163, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, JpMenuLayout.createSequentialGroup()
                .addContainerGap(208, Short.MAX_VALUE)
                .addGroup(JpMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, JpMenuLayout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addGap(173, 173, 173))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, JpMenuLayout.createSequentialGroup()
                        .addComponent(jButtonSairHome)
                        .addContainerGap())))
        );
        JpMenuLayout.setVerticalGroup(
            JpMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(JpMenuLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jButtonSairHome)
                .addGap(47, 47, 47)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addComponent(jLabel2)
                .addGap(48, 48, 48)
                .addGroup(JpMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnQualificacao, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnCorrida, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(263, Short.MAX_VALUE))
        );

        JpClienteCorrida.add(JpMenu, "Tela Principal");

        JpQualificação.setBackground(java.awt.Color.lightGray);
        JpQualificação.setBorder(new javax.swing.border.MatteBorder(null));

        jLabelQualificacao.setFont(new java.awt.Font("Ubuntu", 1, 24)); // NOI18N
        jLabelQualificacao.setText("Sessão de Qualificação:");

        jLabel4.setFont(new java.awt.Font("Ubuntu", 1, 24)); // NOI18N
        jLabel4.setText("Classificação:");

        jLabelRecordQ.setFont(new java.awt.Font("Ubuntu", 1, 24)); // NOI18N
        jLabelRecordQ.setText("Recorde:");

        jLabelAutorQ.setFont(new java.awt.Font("Ubuntu", 1, 24)); // NOI18N
        jLabelAutorQ.setText("Autor:");

        jTQualificacao.setBorder(new javax.swing.border.MatteBorder(null));
        jTQualificacao.setFont(new java.awt.Font("Ubuntu", 0, 24)); // NOI18N
        jTQualificacao.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Pos", "Piloto", "Equipe", "Tempo de volta", "Voltas"
            }
        ));
        jTQualificacao.getTableHeader().setReorderingAllowed(false);
        jScrollPane1.setViewportView(jTQualificacao);
        if (jTQualificacao.getColumnModel().getColumnCount() > 0) {
            jTQualificacao.getColumnModel().getColumn(0).setMinWidth(5);
            jTQualificacao.getColumnModel().getColumn(0).setMaxWidth(60);
        }

        JpVoltarQualificação.setText("Voltar");
        JpVoltarQualificação.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JpVoltarQualificaçãoActionPerformed(evt);
            }
        });

        jButtonSairQuali.setText("Sair");
        jButtonSairQuali.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSairQualiActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout JpQualificaçãoLayout = new javax.swing.GroupLayout(JpQualificação);
        JpQualificação.setLayout(JpQualificaçãoLayout);
        JpQualificaçãoLayout.setHorizontalGroup(
            JpQualificaçãoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(JpQualificaçãoLayout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addGroup(JpQualificaçãoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(JpQualificaçãoLayout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 813, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(JpVoltarQualificação, javax.swing.GroupLayout.DEFAULT_SIZE, 104, Short.MAX_VALUE))
                    .addGroup(JpQualificaçãoLayout.createSequentialGroup()
                        .addGroup(JpQualificaçãoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(JpQualificaçãoLayout.createSequentialGroup()
                                .addComponent(jLabel4)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabelAutorQ))
                            .addGroup(JpQualificaçãoLayout.createSequentialGroup()
                                .addComponent(jLabelQualificacao)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabelRecordQ)))
                        .addGap(178, 178, 178)
                        .addComponent(jButtonSairQuali)))
                .addContainerGap())
        );
        JpQualificaçãoLayout.setVerticalGroup(
            JpQualificaçãoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(JpQualificaçãoLayout.createSequentialGroup()
                .addGroup(JpQualificaçãoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(JpQualificaçãoLayout.createSequentialGroup()
                        .addGap(38, 38, 38)
                        .addGroup(JpQualificaçãoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabelQualificacao)
                            .addComponent(jLabelRecordQ, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(JpQualificaçãoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(jLabelAutorQ))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(JpQualificaçãoLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jButtonSairQuali)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(JpVoltarQualificação, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(18, Short.MAX_VALUE))
        );

        JpClienteCorrida.add(JpQualificação, "Tela de Qualificação");

        JpCorrida.setBackground(java.awt.Color.lightGray);
        JpCorrida.setBorder(new javax.swing.border.MatteBorder(null));

        jLabelCorrida.setFont(new java.awt.Font("Ubuntu", 1, 24)); // NOI18N
        jLabelCorrida.setText("Sessão de Corrida:");

        jLabelClass.setFont(new java.awt.Font("Ubuntu", 1, 24)); // NOI18N
        jLabelClass.setText("Classificação:");

        jLabelRecord.setFont(new java.awt.Font("Ubuntu", 1, 24)); // NOI18N
        jLabelRecord.setText("Recorde:");

        jLabelAutor.setFont(new java.awt.Font("Ubuntu", 1, 24)); // NOI18N
        jLabelAutor.setText("Autor:");

        jTCorrida.setFont(new java.awt.Font("Ubuntu", 0, 24)); // NOI18N
        jTCorrida.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Pos", "Piloto", "Equipe", "Tempo de Volta", "Volta mais rápida", "Voltas"
            }
        ));
        jTCorrida.getTableHeader().setReorderingAllowed(false);
        jScrollPane2.setViewportView(jTCorrida);
        if (jTCorrida.getColumnModel().getColumnCount() > 0) {
            jTCorrida.getColumnModel().getColumn(0).setMinWidth(5);
            jTCorrida.getColumnModel().getColumn(0).setMaxWidth(60);
        }

        btnVoltarCorrida.setText("Voltar");
        btnVoltarCorrida.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVoltarCorridaActionPerformed(evt);
            }
        });

        jButtonSairClass.setText("Sair");
        jButtonSairClass.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSairClassActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout JpCorridaLayout = new javax.swing.GroupLayout(JpCorrida);
        JpCorrida.setLayout(JpCorridaLayout);
        JpCorridaLayout.setHorizontalGroup(
            JpCorridaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(JpCorridaLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(JpCorridaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(JpCorridaLayout.createSequentialGroup()
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 828, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnVoltarCorrida, javax.swing.GroupLayout.DEFAULT_SIZE, 92, Short.MAX_VALUE))
                    .addGroup(JpCorridaLayout.createSequentialGroup()
                        .addGroup(JpCorridaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(JpCorridaLayout.createSequentialGroup()
                                .addComponent(jLabelClass)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabelAutor))
                            .addGroup(JpCorridaLayout.createSequentialGroup()
                                .addComponent(jLabelCorrida)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabelRecord)))
                        .addGap(147, 147, 147)
                        .addComponent(jButtonSairClass)))
                .addContainerGap())
        );
        JpCorridaLayout.setVerticalGroup(
            JpCorridaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(JpCorridaLayout.createSequentialGroup()
                .addGroup(JpCorridaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(JpCorridaLayout.createSequentialGroup()
                        .addGap(36, 36, 36)
                        .addGroup(JpCorridaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabelCorrida)
                            .addComponent(jLabelRecord))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(JpCorridaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabelClass)
                            .addComponent(jLabelAutor))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(JpCorridaLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jButtonSairClass)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnVoltarCorrida, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(24, Short.MAX_VALUE))
        );

        JpClienteCorrida.add(JpCorrida, "Tela de Corrida");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 958, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(JpClienteCorrida, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 569, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(JpClienteCorrida, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnQualificacaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnQualificacaoActionPerformed
        CardLayout cl = (CardLayout) JpClienteCorrida.getLayout();
        cl.show(JpClienteCorrida, "Tela de Qualificação");
        threadQualificacao();
    }//GEN-LAST:event_btnQualificacaoActionPerformed

    private void btnCorridaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCorridaActionPerformed
        CardLayout cl = (CardLayout) JpClienteCorrida.getLayout();
        cl.show(JpClienteCorrida, "Tela de Corrida");
        threadCorrida();
    }//GEN-LAST:event_btnCorridaActionPerformed

    private void JpVoltarQualificaçãoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JpVoltarQualificaçãoActionPerformed
        CardLayout cl = (CardLayout) JpClienteCorrida.getLayout();
        cl.show(JpClienteCorrida, "Tela Principal");
    }//GEN-LAST:event_JpVoltarQualificaçãoActionPerformed

    private void btnVoltarCorridaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVoltarCorridaActionPerformed
       CardLayout cl = (CardLayout) JpClienteCorrida.getLayout();
       cl.show(JpClienteCorrida, "Tela Principal");
    }//GEN-LAST:event_btnVoltarCorridaActionPerformed

    private void jButtonSairHomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSairHomeActionPerformed
        try {
            // TODO add your handling code here:
            rede.enviarDado(cliente.getCliente(), "", "01");
            cliente.fecharConexão();
        } catch (IOException ex) {
            Logger.getLogger(ClientRace.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jButtonSairHomeActionPerformed

    private void jButtonSairQualiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSairQualiActionPerformed
        // TODO add your handling code here:
        try {
            // TODO add your handling code here:
            cliente.fecharConexão();
        } catch (IOException ex) {
            Logger.getLogger(ClientRace.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jButtonSairQualiActionPerformed

    private void jButtonSairClassActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSairClassActionPerformed
        // TODO add your handling code here:
        try {
            // TODO add your handling code here:
            rede.enviarDado(cliente.getCliente(),"", "00");
            cliente.fecharConexão();
        } catch (IOException ex) {
            Logger.getLogger(ClientRace.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jButtonSairClassActionPerformed
    
    private void threadQualificacao(){
        threadQualificacao = new Qualificacao(corrida, jTQualificacao , jLabelQualificacao , jLabelRecordQ , jLabelAutorQ);
        new Thread(threadQualificacao,"qualificacao").start();
    }
    
    private void threadCorrida(){
        threadCorrida = new PainelCorrida(corrida, jTCorrida, jLabelCorrida, jLabelRecord, jLabelAutor);
        new Thread(threadCorrida,"corrida").start();
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) throws IOException {
        /* Set the Nimbus look and feel */
        corrida = new ControllerCorrida();
        rede = new ControllerRede();
        Cliente cliente = new Cliente("172.16.203.2",12345);
        cliente.executa();
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ClientRace().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel JpClienteCorrida;
    private javax.swing.JPanel JpCorrida;
    private javax.swing.JPanel JpMenu;
    private javax.swing.JPanel JpQualificação;
    private javax.swing.JButton JpVoltarQualificação;
    private javax.swing.JButton btnCorrida;
    private javax.swing.JButton btnQualificacao;
    private javax.swing.JButton btnVoltarCorrida;
    private javax.swing.JButton jButtonSairClass;
    private javax.swing.JButton jButtonSairHome;
    private javax.swing.JButton jButtonSairQuali;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabelAutor;
    private javax.swing.JLabel jLabelAutorQ;
    private javax.swing.JLabel jLabelClass;
    private javax.swing.JLabel jLabelCorrida;
    private javax.swing.JLabel jLabelQualificacao;
    private javax.swing.JLabel jLabelRecord;
    private javax.swing.JLabel jLabelRecordQ;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTCorrida;
    private javax.swing.JTable jTQualificacao;
    // End of variables declaration//GEN-END:variables
}
